# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanobot < Formula
  desc "Nanobot cli"
  homepage "https://nanobot.ai"
  version "0.0.1"

  on_macos do
    url "https://github.com/nanobot-ai/nanobot/releases/download/v0.0.1/nanobot_darwin_all.tar.gz"
    sha256 "fd31900bfa4cf0a6d95bf144c86537a8e43d29d6fb071bc651b1516d6bf298a2"

    def install
      bin.install "nanobot"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nanobot-ai/nanobot/releases/download/v0.0.1/nanobot_linux_x86_64.tar.gz"
      sha256 "177f77cc5fcd31c13144483cfb5c873b467ecad9afc1bb14ce713582e2399b34"
      def install
        bin.install "nanobot"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nanobot-ai/nanobot/releases/download/v0.0.1/nanobot_linux_arm64.tar.gz"
      sha256 "15a200ef534352430a0122aaec9a01a5d1cf51feb724aa339b52dbfa25675187"
      def install
        bin.install "nanobot"
      end
    end
  end
end
