# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanobot < Formula
  desc "Nanobot cli"
  homepage "https://nanobot.ai"
  version "0.0.70"

  on_macos do
    url "https://github.com/nanobot-ai/nanobot/releases/download/v0.0.70/nanobot_darwin_all.tar.gz"
    sha256 "e2fd493486ae542beeb6440022a7afb1411b94991e6aaa765645e8ddec3ad3f0"

    def install
      bin.install "nanobot"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nanobot-ai/nanobot/releases/download/v0.0.70/nanobot_linux_x86_64.tar.gz"
      sha256 "0c242968e29b64819f755809412609e7e44888094e6b78fe0fd1b49f9899916a"
      def install
        bin.install "nanobot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nanobot-ai/nanobot/releases/download/v0.0.70/nanobot_linux_arm64.tar.gz"
      sha256 "32e872f189bebda37e297ac95a856f7ffd775c4fbbef3b7aa2b02e7334ea7bf8"
      def install
        bin.install "nanobot"
      end
    end
  end
end
