# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanobot < Formula
  desc "Nanobot cli"
  homepage "https://nanobot.ai"
  version "0.0.53"

  on_macos do
    url "https://github.com/nanobot-ai/nanobot/releases/download/v0.0.53/nanobot_darwin_all.tar.gz"
    sha256 "79f2677af6eabe1c052d63f158e8ce01714cd0d049058fef6b14aa0ae7373fde"

    def install
      bin.install "nanobot"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nanobot-ai/nanobot/releases/download/v0.0.53/nanobot_linux_x86_64.tar.gz"
      sha256 "f6a3c3e14bec58c05d549291f37228677f28d3d0cd5067a99bb7b866aa1bcc8d"
      def install
        bin.install "nanobot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nanobot-ai/nanobot/releases/download/v0.0.53/nanobot_linux_arm64.tar.gz"
      sha256 "ba9579d4b9e25d44ffe0602ce50be3d69eb01eba8f541522b19cfe4743986067"
      def install
        bin.install "nanobot"
      end
    end
  end
end
